Repository wgu-opensource/osmt, pull requests merged in 2022-12, with the labels that each got.

#259 Relax osmt_cli script Java parsing
  osmt_cli.sh
Labels: dev-tooling

#261 Advanced Search Fix
  api/src/main/kotlin/edu/wgu/osmt/config/Constants.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillEsRepo.kt
Labels: bug

#265 Angular code for library export
  ui/src/app/app.module.ts
  ui/src/app/auth/auth-roles.ts
  ui/src/app/navigation/abstract-search.component.ts
  ui/src/app/navigation/commoncontrols.component.html
  ui/src/app/navigation/libraryexport.component.html
  ui/src/app/navigation/libraryexport.component.spec.ts
  ui/src/app/navigation/libraryexport.component.ts
  ui/src/app/richskill/service/rich-skill.service.spec.ts
  ui/src/app/richskill/service/rich-skill.service.ts
  ui/test/resource/mock-data.ts
  ui/test/resource/mock-stubs.ts
Labels: enhancement

#268 Extract API param values to Constants
  api/src/main/kotlin/edu/wgu/osmt/api/model/ApiSortEnum.kt
  api/src/main/kotlin/edu/wgu/osmt/config/Constants.kt
Labels: code quality

#275 Feature/update angular
  ui/package-lock.json
  ui/package.json
Labels: dependencies
