Repository wgu-opensource/osmt, pull requests merged in 2022-02, with the labels that each got.

#149 Fixed error in README
  README.md
Labels: documentation

#152 SonarLint UI fixes
  ui/src/app/collection/collection-table.component.html
  ui/src/app/richskill/import/field-mapping-table.component.html
  ui/src/app/richskill/import/import-preview-table.component.html
  ui/src/app/table/public-table/public-table.component.html
  ui/src/app/table/skills-library-table/skill-table.component.html
Labels: dev-tooling, security-fix

#153 Feature/audit fixes2
  ui/package-lock.json
  ui/package.json
Labels: dev-tooling, security-fix

#162 Remove 'noauth' security config
  api/README.md
  api/src/main/kotlin/edu/wgu/osmt/security/SecurityConfigNoAuth.kt
Labels: bug, dev-tooling, oauth2

#167 Fix error in API README
  api/README.md
Labels: bug, documentation
