Repository wgu-opensource/osmt, pull requests merged in 2023-04, with the labels that each got.

#347 Allow shift-selection of contiguous RSDs
  ui/src/app/table/abstract-table.component.spec.ts
  ui/src/app/table/abstract-table.component.ts
  ui/src/app/table/skills-library-table/skill-table.component.spec.ts
  ui/src/app/table/skills-library-table/skill-table.component.ts
Labels: enhancement

#374 Revert GitHub Hosted Runner to Ubuntu 20.04
  .github/workflows/maven.yml
Labels: bug

#363 OSMT-300: Show categories with totals on collection detail pages.
  api/src/main/kotlin/edu/wgu/osmt/api/model/ApiCollection.kt
  api/src/main/kotlin/edu/wgu/osmt/keyword/Keyword.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillDescriptor.kt
  api/src/test/kotlin/edu/wgu/osmt/api/model/ApiCollectionTest.kt
  docs/int/osmt-v2.x-openapi3.yaml
  ui/src/app/app.module.ts
  ui/src/app/collection/ApiCollection.ts
  ui/src/app/collection/detail/collection-public/collection-public.component.html
  ui/src/app/collection/detail/collection-public/collection-public.component.spec.ts
  ui/src/app/collection/detail/collection-public/collection-public.component.ts
  ui/src/app/collection/detail/manage-collection.component.html
  ui/src/app/collection/detail/manage-collection.component.spec.ts
  ui/src/app/collection/detail/manage-collection.component.ts
  ui/src/app/collection/service/collection.service.ts
  ui/src/app/core/pill/group/pill-group.component.html
  ui/src/app/core/pill/group/pill-group.component.spec.ts
  ui/src/app/core/pill/group/pill-group.component.ts
  ui/src/app/core/pill/pill-control.spec.ts
  ui/src/app/core/pill/pill-control.ts
  ui/src/app/core/pill/pill.component.html
  ui/src/app/core/pill/pill.component.spec.ts
  ui/src/app/core/pill/pill.component.ts
  ui/src/app/richskill/ApiSkill.ts
  ui/src/app/richskill/list/skills-list.component.ts
  ui/src/styles.scss
  ui/test/resource/mock-data.ts
Labels: enhancement

#384 Updates to README for local CI static dataset
  README.md
Labels: documentation, dev-tooling, database
