Repository wgu-opensource/osmt, pull requests merged in 2023-03, with the labels that each got.

#322 Adjust header component test for DOM race condition
  ui/src/app/navigation/header.component.spec.ts
Labels: bug, javascript

#324 Add a static CI dataset, and options in osmt_cli.sh
  osmt_cli.sh
  test/sql/fixed_ci_dataset.sql
Labels: test-coverage, database

#312 Adding filters to RSD Library
  api/src/main/kotlin/edu/wgu/osmt/RoutePaths.kt
  api/src/main/kotlin/edu/wgu/osmt/api/model/ApiSearch.kt
  api/src/main/kotlin/edu/wgu/osmt/config/Constants.kt
  api/src/main/kotlin/edu/wgu/osmt/jobcode/JobCodeEsRepo.kt
  api/src/main/kotlin/edu/wgu/osmt/keyword/Keyword.kt
  api/src/main/kotlin/edu/wgu/osmt/keyword/KeywordEsRepo.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillController.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillDoc.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillEsRepo.kt
  api/src/test/kotlin/edu/wgu/osmt/keyword/KeywordEsRepoTest.kt
  api/src/test/kotlin/edu/wgu/osmt/richskill/RichSkillControllerTest.kt
  api/src/test/kotlin/edu/wgu/osmt/richskill/RichSkillEsRepoTest.kt
  docs/int/osmt-v2.x-openapi3.yaml
  ui/src/app/app.module.ts
  ui/src/app/collection/detail/manage-collection.component.html
  ui/src/app/collection/detail/manage-collection.component.spec.ts
  ui/src/app/collection/detail/manage-collection.component.ts
  ui/src/app/form/form-field-search-select/mulit-select/form-field-search-multi-select.component.ts
  ui/src/app/models/filter-dropdown.model.ts
  ui/src/app/richskill/library/rich-skills-library.component.ts
  ui/src/app/richskill/list/skills-list.component.html
  ui/src/app/richskill/list/skills-list.component.ts
  ui/src/app/richskill/service/rich-skill-search.service.ts
  ui/src/app/richskill/service/rich-skill.service.spec.ts
  ui/src/app/richskill/service/rich-skill.service.ts
  ui/src/app/search/advanced-search/advanced-search.component.spec.ts
  ui/src/app/search/rich-skill-search-results.component.spec.ts
  ui/src/app/search/rich-skill-search-results.component.ts
  ui/src/app/shared/filter-chips/filter-chips.component.html
  ui/src/app/shared/filter-chips/filter-chips.component.scss
  ui/src/app/shared/filter-chips/filter-chips.component.spec.ts
  ui/src/app/shared/filter-chips/filter-chips.component.ts
  ui/src/app/shared/filter-drop-down/filter-dropdown.component.html
  ui/src/app/shared/filter-drop-down/filter-dropdown.component.scss
  ui/src/app/shared/filter-drop-down/filter-dropdown.component.spec.ts
  ui/src/app/shared/filter-drop-down/filter-dropdown.component.ts
  ui/src/app/shared/filter-search/filter-search.component.spec.ts
  ui/src/app/shared/filter-search/filter-search.component.ts
  ui/src/app/shared/index.ts
  ui/src/app/shared/search-multi-select/search-multi-select.component.html
  ui/src/app/shared/search-multi-select/search-multi-select.component.scss
  ui/src/app/shared/search-multi-select/search-multi-select.component.spec.ts
  ui/src/app/shared/search-multi-select/search-multi-select.component.ts
  ui/src/app/shared/shared.module.ts
  ui/src/app/table/filter-controls/filter-controls.component.html
  ui/src/app/table/filter-controls/filter-controls.component.scss
  ui/src/app/table/filter-controls/filter-controls.component.spec.ts
  ui/src/app/table/filter-controls/filter-controls.component.ts
  ui/src/assets/images/down-arrow.svg
  ui/src/assets/images/up-arrow.svg
  ui/test/resource/mock-stubs.ts
  ui/tsconfig.base.json
Labels: enhancement

#331 xit flaky Workspace Header UI test
  ui/src/app/navigation/header.component.spec.ts
Labels: test-coverage

#332 Update curator role description in README
  README.md
Labels: documentation

#329 Show correctly advanced filtered search on dark and light theme
  ui/src/app/shared/filter-chips/filter-chips.component.scss
  ui/src/app/shared/filter-drop-down/filter-dropdown.component.html
  ui/src/app/shared/filter-drop-down/filter-dropdown.component.scss
  ui/src/app/shared/search-multi-select/search-multi-select.component.html
  ui/src/app/shared/search-multi-select/search-multi-select.component.scss
  ui/src/assets/images/down-arrow.svg
  ui/src/assets/images/up-arrow.svg
Labels: bug

#328 Small fix to reindex command and osmt_cli.sh
  api/src/main/kotlin/edu/wgu/osmt/elasticsearch/ReindexCommand.kt
  osmt_cli.sh
Labels: bug, dev-tooling

#339 Correcting Logic for archive/unarchive collection process
  api/src/main/kotlin/edu/wgu/osmt/collection/Collection.kt
  api/src/main/kotlin/edu/wgu/osmt/collection/CollectionRepository.kt
  api/src/main/kotlin/edu/wgu/osmt/db/UpdateObject.kt
  api/src/test/kotlin/edu/wgu/osmt/collection/CollectionControllerTest.kt
  api/src/test/kotlin/edu/wgu/osmt/collection/CollectionUpdateObjectTest.kt
Labels: bug

#326 [Dependent on PR-340] OSMT-301: Added ability to set multiple authors for an RSD
  api/src/main/kotlin/edu/wgu/osmt/api/model/ApiSkill.kt
  api/src/main/kotlin/edu/wgu/osmt/api/model/ApiSkillUpdate.kt
  api/src/main/kotlin/edu/wgu/osmt/csv/BatchImportRichSkill.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillCsvExport.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillDescriptor.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillDescriptorDao.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillDescriptorTable.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillDoc.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillEsRepo.kt
  api/src/main/kotlin/edu/wgu/osmt/richskill/RichSkillRepository.kt
  api/src/main/resources/db/migration/V2023.02.20__richskill-multiple-authors.sql
  api/src/test/kotlin/edu/wgu/osmt/TestObjectHelpers.kt
  api/src/test/kotlin/edu/wgu/osmt/api/model/ApiSkillTest.kt
  api/src/test/kotlin/edu/wgu/osmt/auditlog/AuditLogRepositoryTest.kt
  api/src/test/kotlin/edu/wgu/osmt/collection/CollectionEsRepoTest.kt
  api/src/test/kotlin/edu/wgu/osmt/elasticsearch/ElasticSearchReindexerTest.kt
  api/src/test/kotlin/edu/wgu/osmt/mockdata/MockData.kt
  api/src/test/kotlin/edu/wgu/osmt/mockdata/xml/RichSkillDoc.kt
  api/src/test/kotlin/edu/wgu/osmt/richskill/RichSkillEsRepoTest.kt
  api/src/test/kotlin/edu/wgu/osmt/richskill/RichSkillRepositoryTest.kt
  api/src/test/resources/mock-data.xml
  docs/csv-schema-batchimport-v0.6.x.csvs
  docs/csv-schema-export-v0.6.x.csvs
  docs/csv-schema-upload-v0.6.x.csvs
  docs/int/osmt-v2.x-openapi3.yaml
  ui/src/app/detail-card/detail-card.component.html
  ui/src/app/detail-card/detail-card.component.ts
  ui/src/app/detail-card/title/card-detail-title.component.html
  ui/src/app/detail-card/title/card-detail-title.component.ts
  ui/src/app/richskill/ApiSkill.spec.ts
  ui/src/app/richskill/ApiSkill.ts
  ui/src/app/richskill/ApiSkillUpdate.ts
  ui/src/app/richskill/detail/AbstractRichSkillDetailComponent.spec.ts
  ui/src/app/richskill/detail/AbstractRichSkillDetailComponent.ts
  ui/src/app/richskill/detail/rich-skill-manage/rich-skill-manage.component.html
  ui/src/app/richskill/detail/rich-skill-public/rich-skill-public.component.html
  ui/src/app/richskill/form/rich-skill-form.component.html
  ui/src/app/richskill/form/rich-skill-form.component.spec.ts
  ui/src/app/richskill/form/rich-skill-form.component.ts
  ui/src/app/richskill/import/batch-import.component.html
  ui/src/app/richskill/import/batch-import.component.spec.ts
  ui/src/app/richskill/import/batch-import.component.ts
  ui/src/app/richskill/import/import-preview-table.component.html
  ui/src/app/richskill/service/rich-skill.service.spec.ts
  ui/src/assets/osmt-batch-import-example.csv
  ui/test/resource/mock-data.ts
Labels: enhancement, database, pre-hackathon
