Repository wgu-opensource/osmt, pull requests merged in 2023-05, with the labels that each got.

#375 Feature/osmt 303 category list and detail
  api/src/main/kotlin/edu/wgu/osmt/RoutePaths.kt
  api/src/main/kotlin/edu/wgu/osmt/api/model/ApiKeyword.kt
  api/src/main/kotlin/edu/wgu/osmt/api/model/ApiSortEnum.kt
  api/src/main/kotlin/edu/wgu/osmt/keyword/KeywordController.kt
  api/src/main/kotlin/edu/wgu/osmt/keyword/KeywordDao.kt
  api/src/test/kotlin/edu/wgu/osmt/api/model/ApiKeywordTest.kt
  api/src/test/kotlin/edu/wgu/osmt/keyword/KeywordControllerTest.kt
  docs/int/archive/osmt-v2.x-openapi3.yaml
  docs/int/openapi.yaml
  ui/src/app/abstract.service.ts
  ui/src/app/app-routing.module.ts
  ui/src/app/app.module.ts
  ui/src/app/category/ApiCategory.spec.ts
  ui/src/app/category/ApiCategory.ts
  ui/src/app/category/detail/card/category-detail-card.component.html
  ui/src/app/category/detail/card/category-detail-card.component.spec.ts
  ui/src/app/category/detail/card/category-detail-card.component.ts
  ui/src/app/category/detail/category-detail.component.html
  ui/src/app/category/detail/category-detail.component.spec.ts
  ui/src/app/category/detail/category-detail.component.ts
  ui/src/app/category/index.ts
  ui/src/app/category/library/category-library.component.spec.ts
  ui/src/app/category/library/category-library.component.ts
  ui/src/app/category/list/category-list.component.html
  ui/src/app/category/list/category-list.component.spec.ts
  ui/src/app/category/list/category-list.component.ts
  ui/src/app/category/service/category.service.spec.ts
  ui/src/app/category/service/category.service.ts
  ui/src/app/category/table/category-table.component.html
  ui/src/app/category/table/category-table.component.spec.ts
  ui/src/app/category/table/category-table.component.ts
  ui/src/app/category/table/row/category-table-row.component.html
  ui/src/app/category/table/row/category-table-row.component.spec.ts
  ui/src/app/category/table/row/category-table-row.component.ts
  ui/src/app/navigation/commoncontrols-mobile.component.html
  ui/src/app/navigation/header.component.html
  ui/src/app/navigation/header.component.ts
  ui/src/app/richskill/list/skill-list-row.component.html
  ui/src/app/richskill/list/skill-list-row.component.ts
  ui/src/app/table/abstract-table.component.ts
  ui/src/app/table/control/related-skill-table.control.spec.ts
  ui/src/app/table/control/related-skill-table.control.ts
  ui/src/app/table/control/table.control.ts
  ui/src/app/table/label/select/select-label.component.html
  ui/src/app/table/label/select/select-label.component.spec.ts
  ui/src/app/table/label/select/select-label.component.ts
  ui/src/app/table/label/sort/sort-label.component.html
  ui/src/app/table/label/sort/sort-label.component.spec.ts
  ui/src/app/table/label/sort/sort-label.component.ts
  ui/src/app/table/skills-library-table/skill-table.component.html
  ui/test/resource/mock-stubs.ts
Labels: pre-hackathon

#387 Changes wrap behavior for card heading
  ui/src/styles.scss
Labels: 2023-hackathon

#398 Added CHANGELOG.md
  CHANGELOG.md
Labels: documentation, dev-tooling

#391 OSMT- 276 service classes UI
  docs/int/openapi.yaml
  ui/src/app/abstract.service.spec.ts
  ui/src/app/abstract.service.ts
  ui/src/app/collection/service/collection.service.ts
  ui/src/app/data/abstract-data.service.spec.ts
  ui/src/app/data/abstract-data.service.ts
  ui/src/app/data/named-reference.service.spec.ts
  ui/src/app/data/named-reference.service.ts
  ui/src/app/data/rsd-metadata.enum.ts
  ui/src/app/job-codes/Jobcode.ts
  ui/src/app/job-codes/service/job-code.service.spec.ts
  ui/src/app/job-codes/service/job-code.service.ts
  ui/src/app/richskill/service/keyword-search.service.ts
  ui/src/app/richskill/service/rich-skill.service.ts
  ui/test/resource/mock-data.ts
  ui/tsconfig.base.json
Labels: enhancement

#402 Update OSMT to angular 16
  ui/.browserslistrc
  ui/.eslintrc.json
  ui/.gitignore
  ui/angular.json
  ui/e2e/tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/pom.xml
  ui/src/app/auth/auth.guard.ts
  ui/src/app/collection/service/collection.service.spec.ts
  ui/src/app/core/abstract-form.component.ts
  ui/src/app/form/abstract-form-field.component.spec.ts
  ui/src/app/richskill/service/rich-skill.service.spec.ts
  ui/src/app/shared/search-multi-select/search-multi-select.component.html
  ui/src/app/shared/search-multi-select/search-multi-select.component.spec.ts
  ui/src/polyfills.ts
  ui/src/test.ts
  ui/tsconfig.app.json
  ui/tsconfig.base.json
  ui/tsconfig.json
  ui/tsconfig.spec.json
  ui/tslint.json
Labels: dependencies
