Repository wgu-opensource/osmt, pull requests merged in 2023-06, with the labels that each got.

#415 Update Jasmine from v3 to v4
  ui/package-lock.json
  ui/package.json
  ui/src/app/collection/detail/manage-collection.component.spec.ts
  ui/src/app/richskill/detail/rich-skill-manage/action-bar/action-bar-vertical/manage-skill-action-bar-vertical.component.spec.ts
Labels: dev-tooling, code quality, dependencies, javascript, unit-testing

#416 Update application.properties to remove overly-verbose logging levels
  api/src/main/resources/config/application-dev.properties
  api/src/main/resources/config/application.properties
Labels: dev-tooling

#417 Build correctly URLs for tasks result
  ui/src/app/abstract.service.spec.ts
  ui/src/app/abstract.service.ts
  ui/src/app/collection/service/collection.service.spec.ts
  ui/src/app/richskill/service/rich-skill.service.spec.ts
  ui/test/resource/mock-data.ts
Labels: bug

#423 OSMT 3.0 Changelog
  CHANGELOG.md
Labels: documentation

#424 Add user testing script
  docs/osmt-user-testing-script.md
  docs/osmt-user-testing-script.xlsx
Labels: documentation, test-coverage

#425 Add additional testing paths for 3.0.0 features
  docs/osmt-user-testing-script.md
  docs/osmt-user-testing-script.xlsx
Labels: test-coverage

#427 Refactor osmt_cli functions into common lib
  bin/lib/common.sh
  osmt_cli.sh
Labels: dev-tooling

#399 Fix UI tests: Cannot match any routes
  ui/src/app/my-workspace/my-workspace.component.spec.ts
Labels: unit-testing

#395 New Feature: Infrastructure Recipe for AWS cloud deployment
  infra/aws/.gitignore
  infra/aws/README.md
  infra/aws/terraform/invocation/config.auto.tfvars.json.tpl
  infra/aws/terraform/invocation/main.tf.tpl
  infra/aws/terraform/invocation/secrets.auto.tfvars.json.tpl
  infra/aws/terraform/invocation/variables.tf
  infra/aws/terraform/module/alb.tf
  infra/aws/terraform/module/cloudwatch.tf
  infra/aws/terraform/module/config.tf
  infra/aws/terraform/module/data.tf
  infra/aws/terraform/module/ecs.tf
  infra/aws/terraform/module/elasticache.tf
  infra/aws/terraform/module/iam.tf
  infra/aws/terraform/module/locals.tf
  infra/aws/terraform/module/rds.tf
  infra/aws/terraform/module/secrets.tf
  infra/aws/terraform/module/security_groups.tf
  infra/aws/terraform/module/templates/container_definition_app.json.tpl
  infra/aws/terraform/module/templates/container_definition_elasticsearch.json.tpl
  infra/aws/terraform/module/vpc.tf
Labels: howto, 2023-hackathon
